### ISSUE TITLE
Request for Pre-trained Models, Evaluation Code, and Detailed Instructions for RDE Generation from PPFlow Backbones

### ISSUE THREAD

**Issue by BL-Lac149597870** [EDAPINENUT/ppflow#2]
First off, I would like to express my admiration for this project; it's truly impressive and has been incredibly useful.

I have a few requests that could potentially enhance the usability and accessibility of the project for users like myself and others:

1. **Pre-trained Models**: Could you provide any pre-trained models that could be used to quickly get up and running with the project? This would be immensely helpful, especially for newcomers wanting to test the capabilities without going through the full training process.

2. **Evaluation Code**: It would be beneficial if you could share the scripts or code used for evaluating the model results. Having access to this would help in understanding how to measure the performance and effectiveness of the model in various scenarios.

3. **RDE Generation Code**: I am particularly interested in how to use the skeletons generated by PPFlow for RDE-based side chain generation. Could you provide some examples or detailed guidance on how to implement this process using your framework?

Thank you for considering these requests. I believe these additions could make the project even more valuable for the community.

**Comment by EDAPINENUT** [comment]
Your request has been put into the process, but we haven’t fully resolved it yet. We will notify you once everything is resolved.

**Comment by BL-Lac149597870** [comment]
Thanks very much!
