### ISSUE TITLE
Missing pretrained.pt file in Google Drive

### ISSUE THREAD

**Issue by BL-Lac149597870** [EDAPINENUT/ppflow#3]
### Issue Description
The pretrained model file `ppflow_pretrained.pt`, as referenced in the repository's documentation, is missing from the specified Google Drive link.

### Steps to Reproduce
1. Followed the Google Drive link provided in the section 'Generating from pretrained checkpoints'.
2. Attempted to locate and download the `ppflow_pretrained.pt` file.
3. The file was not present in the drive.

### Expected Behavior
The file `ppflow_pretrained.pt` should be available for download as indicated in the documentation.

### Actual Behavior
The file is not available in the Google Drive directory.

### Proposed Solution/Query
Could you please confirm if the file has been moved or is no longer available? If possible, please provide a new link to download the pretrained model.

Thank you!

**Comment by EDAPINENUT** [comment]
We have not yet responded to your previous message because we are currently working on addressing the issues you raised one by one. Please be patient, and once everything is resolved, we will reply in the issue.

**Comment by BL-Lac149597870** [comment]
Thanks very much!!
