### ISSUE TITLE
Device problems.

### ISSUE THREAD

**Issue by jdp22** [EDAPINENUT/ppflow#7]
Hi! There are lots of "Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!" when I try to use the pre-trained model in the inference stage, please help recheck your code and fix them.

**Comment by EDAPINENUT** [comment]
Please provide the specific error message. Additionally, if the error is related to geomstats, please refer to  https://github.com/EDAPINENUT/ppflow/issues/1.
